language: ruby
sudo: false
rvm:
  - 2.3.3
  - 2.5.0
script:
  - cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:migrate
  - cd ../.. && bundle exec rspec spec
addons:
  chrome: stable
before_install:
  - gem install chromedriver-helper
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
deploy:
  provider: rubygems
  api_key:
    secure: PEMMDcT4SKPdv4xMJmIEpndOGePsV3kDOhUL0vEDjTeyxBrn+iBgHKF9itSYbUmOSTuOaiIVleYmuC6GoAmg4KcZIZvfCA61cGCX1ADU5nwh5FjC/tAEs8eShMR3RFG6wyykb4MdFkE2jVpm/W0pyciLgW2HrM6iYzI6X2iMn9E=
  gem: activeadmin_addons
  on:
    tags: true
    repo: platanus/activeadmin_addons
before_script:
  - chromedriver-update 73.0.3683.68
